parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Authentication\Application\CreateUser\CreateUserCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Application\ChangeUserEmail\ChangeUserEmailCommandHandler:
        tags: [ messenger.message_handler ]
        arguments:
            $secret: '%env(APP_SECRET)%'

    App\Authentication\Application\ChangeUserPassword\ChangeUserPasswordCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Application\VerifyUserEmail\VerifyUserEmailCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Application\AuthenticateUser\AuthenticateUserCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Application\SendUserEmailVerificationEmail\UserEmailChangedEventHandler:
        tags: [ messenger.message_handler ]
        arguments:
            $sender: '%env(MAILER_SENDER)%'

    App\Authentication\Application\SendUserDeactivationEmail\UserDeactivatedEventHandler:
        tags: [ messenger.message_handler ]
        arguments:
            $sender: '%env(MAILER_SENDER)%'

    App\Authentication\Application\DeactivateUser\DeactivateUserCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Application\ActivateUser\ActivateUserCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Application\ConsumeOutboxMessages\ConsumeOutboxMessagesCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Infrastructure\Doctrine\UserRepository: ~
    App\Authentication\Infrastructure\Symfony\UserPasswordValidator: ~
    App\Authentication\Infrastructure\Symfony\UserPasswordHasher: ~
    App\Authentication\Infrastructure\Symfony\SecurityUserProvider: ~
    App\Authentication\Infrastructure\Lexik\JwtTokenCreator: ~
    App\Shared\Infrastructure\Symfony\UuidCreator: ~
    App\Shared\Infrastructure\Symfony\Bus\Even\EventBus: ~
    App\Shared\Infrastructure\Symfony\EmailSender: ~
    App\Shared\Infrastructure\Symfony\UrlCreator: ~
    App\Shared\Infrastructure\Doctrine\OutboxMessageRepository: ~

    App\Authentication\Domain\UserRepositoryInterface: '@App\Authentication\Infrastructure\Doctrine\UserRepository'
    App\Authentication\Domain\UserPasswordValidatorInterface: '@App\Authentication\Infrastructure\Symfony\UserPasswordValidator'
    App\Authentication\Domain\JwtTokenCreatorInterface: '@App\Authentication\Infrastructure\Lexik\JwtTokenCreator'
    App\Authentication\Domain\UserPasswordHasherInterface: '@App\Authentication\Infrastructure\Symfony\UserPasswordHasher'
    App\Shared\Domain\OutboxMessageRepositoryInterface: '@App\Shared\Infrastructure\Doctrine\OutboxMessageRepository'
    App\Shared\Infrastructure\Symfony\UuidCreatorInterface: '@App\Shared\Infrastructure\Symfony\UuidCreator'
    App\Shared\Infrastructure\Symfony\Bus\Even\EventBusInterface: '@App\Shared\Infrastructure\Symfony\Bus\Even\EventBus'
    App\Shared\Infrastructure\Symfony\UrlCreatorInterface: '@App\Shared\Infrastructure\Symfony\UrlCreator'
