# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Authentication\Application\CreateUser\CreateUserCommandHandler:
        tags: [messenger.message_handler]
    App\Authentication\Application\ChangeUserEmail\ChangeUserEmailCommandHandler:
        tags: [ messenger.message_handler ]
    App\Authentication\Application\ChangeUserPassword\ChangeUserPasswordCommandHandler:
        tags: [ messenger.message_handler ]
    App\Authentication\Application\VerifyUserEmail\VerifyUserEmailCommandHandler:
        tags: [ messenger.message_handler ]
    App\Authentication\Application\AuthenticateUser\AuthenticateUserCommandHandler:
        tags: [ messenger.message_handler ]
    App\Authentication\Application\SendUserEmailVerificationEmail\UserEmailChangedEventHandler:
        tags: [ messenger.message_handler ]
        arguments:
            $secret: '%env(APP_SECRET)%'
            $sender: '%env(MAILER_SENDER)%'
    App\Authentication\Application\SendUserDeactivationEmail\UserDeactivatedEventHandler:
        tags: [ messenger.message_handler ]
        arguments:
            $sender: '%env(MAILER_SENDER)%'
    App\Authentication\Application\DeactivateUser\DeactivateUserCommandHandler:
        tags: [ messenger.message_handler ]
    App\Authentication\Application\ActivateUser\ActivateUserCommandHandler:
        tags: [ messenger.message_handler ]

    App\Authentication\Infrastructure\Doctrine\UserRepository: ~
    App\Authentication\Domain\UserRepositoryInterface: '@App\Authentication\Infrastructure\Doctrine\UserRepository'
